config/routes.rb
Rails.application.routes.draw do
  resources :reserves
  resources :customers
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :identification, presence: true, numericality: true
  validates :cellphone, presence: true, numericality: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :url, presence: true
end

app/models/reserve.rb
class Reserve < ApplicationRecord
    validates :date, presence: true
    validates :movie_id, presence: true, numericality: true
    validates :customer_id, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Cliente creado' }
      end
    end
  end

  private
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :email, :identification, :cellphone)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.all
    @movie = Movie.new
  end
 
  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Pelicula añadida' }
      end
    end
  end

  private

    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:name, :description, :url, :date)
    end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  before_action :set_reserf, only: [:show, :edit, :update, :destroy]

  def index
    @reserves = Reserve.all
    @reserf = Reserve.new
  end

  def new
    @reserf = Reserve.new
  end

  def create
    @reserf = Reserve.new(reserf_params)

    respond_to do |format|
      if @reserf.save
        format.html { redirect_to @reserf, notice: 'Pelicula reservada' }
      end
    end
  end

  private
    def set_reserf
      @reserf = Reserve.find(params[:id])
    end

    def reserf_params
      params.require(:reserf).permit(:date, :movie_id, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name, placeholder: "Nombre", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.text_field :email, placeholder: "Email", class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.number_field :identification, placeholder: "Cédula", class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.number_field :cellphone, placeholder: "Célular", class: 'form-control'  %>
  </div>

  <div class="actions">
    <%= form.submit 'Crear Cliente', class: 'btn btn-primary' %>
    <%= link_to 'Atras', customers_path, class: 'btn btn-primary' %>
  </div>


<% end %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Identification</th>
      <th>Cellphone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.identification %></td>
        <td><%= customer.cellphone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cliente', new_customer_path, class: 'btn btn-primary' %>

app/views/customers/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Identification:</strong>
  <%= @customer.identification %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @customer.cellphone %>
</p>

<%= link_to 'Volver', customers_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cinema</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
  <div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Cinema</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Movies', movies_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Customers', customers_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Reserves', reserves_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
    <%= yield %>
    </div>
  </body>
</html>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peliculas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.description %></td>
        <td><%= movie.url %></td>
        <td><%= movie.date %></td>
        <td><%= link_to 'Ver', movie %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'Crear pelicula', new_movie_path %>-->

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Crear pelicula
</button>

<%= form_for(@movie, url: movies_path, method: :post ) do |f| %>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Agregar pelicula</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_field :name, placeholder: "Nombre", :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.text_field :description, placeholder: "Descripción", :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.text_field :url, placeholder: "URL", :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.date_select :date, placeholder: "Fecha (dd/mm/yyyy)", :class => 'form-control'%>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Aceptar", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @movie.url %>
</p>

<p>
  <strong>Date:</strong>
  <%= @movie.date %>
</p>

<%= link_to 'Volver', movies_path, class: 'btn btn-primary' %>

app/views/reserves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reserves</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Movie</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reserves.each do |reserf| %>
      <tr>
        <td><%= reserf.date %></td>
        <td><%= reserf.movie_id %></td>
        <td><%= reserf.customer_id %></td>
        <td><%= link_to 'Show', reserf %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Reservar pelicula
</button>

<%= form_for(@reserf, url: reserves_path, method: :post ) do |f| %>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Reservar</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <%= f.date_select :date, placeholder: "Fecha (dd/mm/yyyy)" %>
          </div>
          <div class="form-group">
            <%= f.collection_select(:movie_id, Movie.all, :id, :name, {include_blank: true}, {class: 'form-control'}) %>
          </div>
          <div class="form-group">
            <%= f.collection_select(:customer_id, Customer.all, :id, :name, {include_blank: true}, {class: 'form-control'}) %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Aceptar", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/reserves/new.html.erb
<h1>New Reserf</h1>

<%= render 'form', reserf: @reserf %>

<%= link_to 'Back', reserves_path %>

app/views/reserves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @reserf.date %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @reserf.movie_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @reserf.customer_id %>
</p>

<%= link_to 'Edit', edit_reserf_path(@reserf) %> |
<%= link_to 'Back', reserves_path %>